#!/bin/bash
source "${APIGEE_ROOT}/apigee-lib/apigee-lib.sh" || exit 1
source "${APIGEE_ROOT}/apigee-lib/dofflag.sh" || exit 1

TOKEN_DIR="${APIGEE_ROOT}/token/application"
TOKEN_FILE="${TOKEN_DIR}/${APPLICATION}.properties"

validate_vars "${APIGEE_PREFIX}${APPLICATION}" "disable-ssl" || exit 1
echo "Disabling HTTPS for UI services"

replace_var "${TOKEN_FILE}" "conf_apigee-base_apigee.feature.usehttps" "\"false\""  || exit 1

ETC_DIR="$APIGEE_ROOT/etc/${APIGEE_PREFIX}${APPLICATION}.d"

if [ -e "$ETC_DIR/SSL.sh" ]; then
    rm "$ETC_DIR/SSL.sh" || exit 1
fi

echo "Restarting UI service"
CHECKED_CALL \
"$APIGEE_ROOT/apigee-service/bin/apigee-service" "$COMPONENT_NAME" restart

CHECKED_CALL \
"$APIGEE_ROOT/apigee-service/bin/apigee-service" "$COMPONENT_NAME" wait_for_ready

echo "HTTPS for UI successfully disabled"
